# hpa.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: httpd-hpa
  namespace: my-app-project
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: httpd-simple-metrics
  minReplicas: 1
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 10
      policies:
      - type: Percent
        value: 10
        periodSeconds: 5
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 80
        periodSeconds: 7
      - type: Pods
        value: 4
        periodSeconds: 10
      selectPolicy: Max
  